# -*- coding: utf-8 -*-
"""Individual project- Grace Ogundaini

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-HGJftXh6STH7nHb4ifldQunlg9hGL9

#Automating Accounting Procedures for a Business

A local retail business, dealing with a variety of products, aims to streamline and automate its accounting procedures. The business operates two shifts per day with one worker on each shift. The primary goal is to create a Python project that assists in automating essential accounting tasks, including calculating total sales, worker salaries, profit, tips, and total tips for the day.
"""

import pandas as pd

#importing the dataset fom google drive and passing it into a dataframe
dataset = '/content/drive/MyDrive/Local retail business.xlsx'
df = pd.read_excel(dataset)
df.head()

#calculating total sales for the day
def calculate_total_sales():
  total_sales = df["Sales"].sum()
  print(f"Total sales is: ${total_sales}")
calculate_total_sales()

# calculating worker's salary based on input
def calculate_worker_salary():
    worker_name = input("Enter worker's name: ")
    hourly_rate = float(input("Enter hourly rate: "))
    hours_worked = float(input("Enter hours worked: "))
    worker_salary = hourly_rate * hours_worked
    print(f"{worker_name}'s Salary: ${worker_salary}")

#calculating total profit
def calculate_profit():
    total_sales = df['Sales'].sum()
    total_cost = df['CostOfItemsSold'].sum()
    profit = total_sales - total_cost
    print(f"Profit: ${profit}")

#calculating total tips
def calculate_tips_for_shift():
    shift_sales = float(input("Enter shift sales: "))
    tips = 0.02 * shift_sales
    print(f"Tips for the Shift: ${tips}")

#calculating total tips for the day
def calculate_total_tips_for_day():
    total_tips_day = df['Tips'].sum()
    print(f"Total Tips for the Day: ${total_tips_day}")

# user options
def display_menu():
    print("\nMenu:")
    print("1. Calculate Total Sales for the Day")
    print("2. Calculate Worker's Salary")
    print("3. Calculate Profit")
    print("4. Calculate Tips for a Shift")
    print("5. Calculate Total Tips for the Day")
    print("6. Exit")

#main code
def main():
    while True:
        display_menu()
        choice = input("Enter your choice (1-6): ")

        if choice == '1':
            calculate_total_sales()
        elif choice == '2':
            calculate_worker_salary()
        elif choice == '3':
            calculate_profit()
        elif choice == '4':
            calculate_tips_for_shift()
        elif choice == '5':
            calculate_total_tips_for_day()
        elif choice == '6':
            print("Exiting the program. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 6.")

if __name__ == "__main__":
    main()